name: Build and test C

on:
  push:
    branches: [ main, stable, oldstable ]
  pull_request:
    branches: [ main, stable, oldstable ]


jobs:
  c_format_check:
    env:
      WORKSPACE: ${{ github.workspace }}/gsad
    name: Check C Source Code Formatting
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Check Source Format
        run: |
          clang-format -i -style=file ${{ env.WORKSPACE }}/src/*.{c,h} \
          && git diff --exit-code
  build_gsad:
    env:
      WORKSPACE: ${{ github.workspace }}/gsad
    name: Build gsad
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        container:
          - greenbone/gsa-stable-gcc-testing
          - greenbone/gsa-stable-clang-testing
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Configure and compile gsad
        run: |
          mkdir build && rm -rf .git && cd build/ \
            && cmake -DCMAKE_BUILD_TYPE=Release .. && make install
        working-directory: ${{ env.WORKSPACE }}
  build_full:
    name: Build gsa and gsad from root dir
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        build_type:
          - Debug
          - Release
        container:
          - greenbone/gsa-stable-gcc-testing
          - greenbone/gsa-stable-clang-testing
    container: ${{ matrix.container }}
    env:
      BUILD_TYPE: ${{ matrix.build_type }}
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Configure and compile
        run: |
          mkdir build && rm -rf .git && cd build/ \
            && cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE .. && make install
        working-directory: ${{ github.WORKSPACE }}
